### ISSUE TITLE
Adding Qualtrics and Google Forms as Providers 

### ISSUE THREAD

**Issue by rrojas350** [BrightSpots/rcv#599] opened 2022-05-09 20:34 UTC
Some organizations, such as colleges, use RCTab to tabulate results generated by Qualtrics and Google Forms. However, the CVR file generated by these two inverts the data from that of an ES&S file.

On a Qualtrics/Google Forms CVR, the columns are candidate names and the cells contain the ranking number. 

See comments on #549

**Comment by chughes297** [comment] 2023-02-16 18:45
I think this can be merged with #549

**Comment by tarheel** [comment] 2023-02-22 21:18
closing as duplicate of #549

**Closed by tarheel** 2023-02-22 21:18 UTC
Labels: enhancement, v1.4 requirement, v1.4 Nice-to-Have P1
