### ISSUE TITLE
fix noinspection unchecked for excluded CheckBox in GuiConfigController

### ISSUE THREAD

**Issue by tarheel** [BrightSpots/rcv#304] opened 2019-06-23 06:48 UTC

**Comment by HEdingfield** [comment] 2019-06-23 07:40
This applies to `GuiConfigController.initialize()`:
```
// noinspection unchecked
return new SimpleObjectProperty(checkBox);
```

**Comment by HEdingfield** [comment] 2020-07-15 18:11
I believe this was also resolved with #462.

**Comment by HEdingfield** [comment] 2020-07-29 16:24
The "fix" in #462 resolved the warning, but it also broke checkboxes in the Candidates table (now they only appear as "true" or "false" and it's uneditable. Need to roll this back.

**Comment by HEdingfield** [comment] 2020-08-09 19:16
Duplicate of #280.

**Closed by HEdingfield** 2020-08-09 19:16 UTC
Labels: 1.2.0 deliverable, code cleanup
