### ISSUE TITLE
"Hints for this tab" Improvements/Tool Tips Improvements

### ISSUE THREAD

**Issue by rrojas350** [BrightSpots/rcv#595] opened 2022-05-09 17:44 UTC
Highlight or bold the hint relevant to the field the user is working in. E.g. If the User is entering info in Contest Name, the Hint "Contest Name (Required):..." is bolded for quick reference. 

Alternatively, Hints could be removed and an icon for more information "ⓘ" could be placed in each field with a hint available.

**Comment by HEdingfield** [comment] 2024-02-28 02:38
Duplicate of #513.

**Closed by HEdingfield** 2024-02-28 02:38 UTC
Labels: enhancement, 2022 User Group
