### ISSUE TITLE
Error w/CDF files in v1.3 

### ISSUE THREAD

**Issue by rrojas350** [BrightSpots/rcv#627] opened 2023-02-07 22:28 UTC
When tabulating a Unisyn CDF CVR in RCTab v1.3 this error occurs:
"javax.xml.stream.FactoryConfigurationError: Provider for javax.xml.stream.XMLInputFactory cannot be found
Tabulation failed!"

The same CVR will tabulate correctly in v1.2. The error occurs when loading a saved config and when starting from square one.  See the attached audit log for more info. 
[2023-02-07_14-18-13_audit_0.log](https://github.com/BrightSpots/rcv/files/10679879/2023-02-07_14-18-13_audit_0.log)

**Comment by tarheel** [comment] 2023-02-07 22:56
duplicate of #625

**Closed by tarheel** 2023-02-07 22:56 UTC
Labels: bug, cdf
