### ISSUE TITLE
Input CVR file name containing % fails tabulation: java.util.MissingFormatArgumentException: Format specifier '%2C'

### ISSUE THREAD

**Issue by andyanderson** [BrightSpots/rcv#564] opened 2021-04-18 16:12 UTC
I’m working with output files from Qualtrics, which URL-encodes contest names (I assume to ensure cross-platform file name compatibility). An example is:

What+Are+Your+Favorite+Fruits+and+Vegetables%3F_April+13%2C+2021_23.28_Fruits.csv

The %3F is '?’ and %2C is ','. 

I’ve converted this to ES&S input format and resaved as Excel. When I validate, all is well. But when I tabulate, I get the following error:

java.util.UnknownFormatConversionException: Conversion = 'F'
Tabulation failed!

If I shorten the file name to just “April+13%2C+2021_23.28_Fruits.csv”, I get this error:

java.util.MissingFormatArgumentException: Format specifier '%2C'
Tabulation failed!

If I shorten the file name to just “Fruits.csv”, tabulation succeeds.

Apparently the file is being read by a different routine for tabulation than for validation, and the former isn’t taking care to protect the file name from attempted string formatting.

Attaching sample input files.

[What+Are+Your+Favorite+Fruits+and+Vegetables%3F_April+13%2C+2021_23.28_Fruits.zip](https://github.com/BrightSpots/rcv/files/6331672/What%2BAre%2BYour%2BFavorite%2BFruits%2Band%2BVegetables.3F_April%2B13.2C%2B2021_23.28_Fruits.zip)

**Comment by tarheel** [comment] 2021-04-19 05:20
Thanks for flagging. We actually got the same report just recently from another source. Closing this because it's a duplicate of #561.

**Closed by tarheel** 2021-04-19 05:20 UTC

**Comment by moldover** [comment] 2022-06-07 01:54
@HEdingfield + @andyanderson yep - was able to tabulate:

2022-06-06 18:53:47 PDT INFO: Round: 4
2022-06-06 18:53:47 PDT INFO: Winning threshold set to 14.
2022-06-06 18:53:47 PDT INFO: Candidate "Strawberry" got 15 vote(s).
2022-06-06 18:53:47 PDT INFO: Candidate "Grapefruit" got 11 vote(s).
2022-06-06 18:53:47 PDT INFO: Candidate "Strawberry" was elected in round 4 with 15 votes.

Congratulations to Strawberry.
