### ISSUE TITLE
Improve forensics / reproducibility of output

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#43] opened 2018-04-12 17:11 UTC
Forensics is critical: output should include details on the machine/system, version, date/time, config file, etc. In addition to log and results visualizer files, also output the config file used for tabulation.

**Comment by HEdingfield** [comment] 2018-05-21 18:47
It's also probably really important that we ensure any future versions of the tabulator are backwards-compatible with older config files. Should we open a separate issue for this?

**Comment by tarheel** [comment] 2018-05-21 19:54
> It's also probably really important that we ensure any future versions of the tabulator are backwards-compatible with older config files. Should we open a separate issue for this?

Yes. I would say once we have any actual external users, we should start supporting config versions. But for now the config format is still changing quite a bit...

**Comment by moldover** [comment] 2018-05-22 05:27
Good call, we should def spit out the config, version (date/time is in every log statement, but sure).  I'm not sure what aspects of the system are relevant, but certainly current user, working directory and input/output file hashes when we have them.

As for versions, that's another good point.  I agree with Louis, things are way too in flux, and no external users to justify this yet, but we should plan on it.  I'm not convinced we need to be backwards compatible in general.  It's totally reasonable to expect users who want to run old configs to use an older version of the tabulator.  That said, we may as well and add a version number to the config so it's available when we do break something.

**Comment by HEdingfield** [comment] 2019-02-14 07:27
This popped into my consciousness again when working on stuff recently: we should output the config file along with the csv and visualizer json whenever we run the tabulator.

**Comment by nealmcb** [comment] 2019-04-08 16:47
Most important is transparency around backwards-compatiibility.  I recommend semantic versioning: you get to do backwards-incompatible changes, but have to make it obvious to the users.

See also comments in #170 since getting any necessary randomness to be generated and reported in a reproducible fashion is tricky and important.  See e.g. Rivest's "sampler" PRNG at https://github.com/nealmcb/rivest-sampler-tests/tree/python3-port

**Comment by gngilbert** [comment] 2019-06-09 18:22
Not sure how much we can or need to accomplish for this round of testing but I think this needs to be addressed seriously asap.

**Comment by HEdingfield** [comment] 2019-06-13 05:28
We'll:
- Adopt semantic versioning (this first certification deliverable will be tagged as 1.0.0)
- Include RCV Tabulator version in the log
- Spit raw contents of config file into log
- Try to include info on machine / OS running the tabulation in the log

TBD:
- Including RCV Tabulator version in the config files somehow

**Comment by HEdingfield** [comment] 2019-06-18 16:09
Something worth noting: once we merge in PR #287 with version 1.0.0 hardcoded in there, we can't generate any pre-compiled versions until we're done done. We definitely don't want multiple 1.0.0s running around out there. I'll make a note to generate a Linux jlink today if I get a chance with the repo in its current state.

This also makes me realize that once we release 1.0.0, we'll need to maintain a separate `dev` branch and treat that as our new `master`. Only when we're ready to increment the version number should we merge all changes from the `dev` branch into `master`.

**Comment by HEdingfield** [comment] 2019-06-18 16:51
Went ahead and created `develop` branch now to start us on the GitFlow release management path, per #289.

**Comment by moldover** [comment] 2019-06-19 06:09
So, that's a good point on #287.  I just updated the version to 0.1.0 in the branch for #287 so that is not a problem.  Once we're at code freeze for submission we can update the build version to 1.0.0.

As for using git flow, it looks fine, but with just the three of us I don't see it adding more value than overhead.

**Comment by HEdingfield** [comment] 2019-06-19 06:15
It shouldn't be too much more overhead I don't think; the main thing is to just treat the develop branch now the way we used to treat the master branch. Then when it comes time to do releases, we tag with the version number and merge into master. I'm happy to spearhead the releases if you don't want to deal with them. I use Gitflow a lot in my personal projects, so I'm pretty used to it.

**Comment by moldover** [comment] 2019-06-19 15:01
Gotcha.  Well, if @tarheel is game I'll give it a shot.

**Comment by nealmcb** [comment] 2019-06-19 19:22
We've found in other projects that having the build system generate and insert the release number is super helpful for debugging and development in general. There are a bunch of ways to do that, including ways which put git commit info in the string for dev builds and the like, so you don't have to hardcode the strings. I can dig more out if you're interested.

**Comment by nealmcb** [comment] 2019-06-19 19:26
For what its worth, as I recall the projects I've been on weren't thrilled with approaches like GitFlow, finding them too heavyweight. See also [GitFlow considered harmful | End of Line Blog](https://www.endoflineblog.com/gitflow-considered-harmful)

**Comment by tarheel** [comment] 2019-06-19 19:36
I'll admit I haven't spent much time thinking this through... but I'm pretty receptive to the argument in the blog post that @nealmcb just shared. GitFlow does feel kind of over-engineered.

**Comment by HEdingfield** [comment] 2019-06-19 22:22
The article brings up a few good points, but I thoroughly disagree with it's conclusion and his proposed alternative. Imagine this (very likely) scenario if we continue as-is:
- We tag a release as 1.0.0 on master.
- We don't use Gitflow, and instead just keep merging with the master branch directly.
- We're not ready to release 1.1.0 yet, but someone downloads and compiles our repo after we've made some post-1.0.0 changes and then files a bug report saying it happened with 1.0.0.

This is obviously a terrible situation, because it's not really 1.0.0 they downloaded and compiled, but 1.0.0 plus whatever other changes we made whenever they downloaded it, which requires tons of extra forensics / debugging back-and-forth.

So this turns into us needing to increment the release number every single time we merge from a feature branch to master, which is a) a pain in the ass to remember, and b) even worse if the three of us are working on three separate feature branches at once.

By simply keeping this stream of work to the develop branch, we avoid this problem, because we'll be totally synced up on when we're ready to do an official next release on master. I promise it's not going to be that complicated or "over-engineered". As I said above, the only practical difference for your day-to-day coding will be basing your PRs off develop instead of master.

**Comment by tarheel** [comment] 2019-06-19 22:32
Not contesting your last point about the practical difference of this approach -- I'll take your word for it -- but I'm not sure that the hypothetical situation you described would actually be a problem. If a random person compiled master on their own and then filed a bug, couldn't we just ask them for the commit hash that their build was based on? Anyone technical enough to compile on their own instead of using our official releases should also be capable of telling us what exactly they compiled...

**Comment by nealmcb** [comment] 2019-06-19 23:03
I agree that version numbers should not be misleading, which is why I noted the option above of having them generated automatically by git-savvy build tools which can actually lead users to the exact version of source code involved even for dev builds. But of course I don't really have much of a stake in the decision - just hoping some extra input may be helpful.

E.g. this looks good for Gradle-based builds: https://ryanharter.com/blog/2013/07/30/automatic-versioning-with-git-and-gradle/

and this is another option: https://medium.com/@passsy/use-different-build-numbers-for-every-build-automatically-using-a-gradle-script-35577cd31b19

**Comment by HEdingfield** [comment] 2019-06-19 23:31
@tarheel: why even allow that confusing situation in the first place though? It's much cleaner, straightforward, and simple to have a guarantee than anyone building off the master branch will be at a static, known position. There's literally no downside in our case other than simply remembering to base most of our PRs on the develop branch, and I offered to double-check that...

@nealmcb: I don't anticipate doing new releases all that often at this point, so version number automation is probably unnecessary right now. Good to know for future reference though.

**Comment by tarheel** [comment] 2019-06-19 23:43
> There's literally no downside in our case other than simply remembering to base most of our PRs on the develop branch, and I offered to double-check that.

OK!

**Comment by HEdingfield** [comment] 2019-06-22 16:46
@moldover: I agree with you in #295 on adding the version number to the config files; we could probably just make a fifth top level key, `tabulatorVersion`.

A small wrinkle will be deciding how this gets updated when a different version of the tabulator loads it: I think we should probably have it automatically update the version number once it loads, but since it's a field in the background, it'll seem to the user like it's unnecessarily asking them to save changes (which is a small nuisance judging by #279).

**Comment by tarheel** [comment] 2019-06-23 07:21
> A small wrinkle will be deciding how this gets updated when a different version of the tabulator loads it: I think we should probably have it automatically update the version number once it loads, but since it's a field in the background, it'll seem to the user like it's unnecessarily asking them to save changes (which is a small nuisance judging by #279).

When this is the only change, maybe we can tell the user what's going on so they're not confused.

**Comment by moldover** [comment] 2019-06-28 15:29
For the config version I say use semantic versioning here as well. As Hylton suggests, a top level key/string in the config json, "version" : "1.0.0"

In general we should log whenever we are adding default values during loading to alert the user as Louis suggests and to keep a record of where data changes come from.

**Comment by tarheel** [comment] 2019-06-28 16:51
> In general we should log whenever we are adding default values during loading to alert the user as Louis suggests and to keep a record of where data changes come from.

Would this require switching to a different JSON library? Or is there a setting in Jackson to tell it not to fill in default values when fields are missing?

**Comment by HEdingfield** [comment] 2019-06-28 18:51
I thought this was exactly why we moved away from doing default values. @moldover, can you explain when this would be an issue? Once the changes in #211 are implemented, we'll never have a case where there are unspecified fields in a config file. Or are you specifically discussing the situation where a new "if not supplied" field is added in a future version?

**Comment by moldover** [comment] 2019-07-04 23:35
@HEdingfield circling back on this finally.  Is your question above still relevant now that #211 is done?  

As for the config version update behavior, I agree, if someone loads an older version we can update it to the current version and log why.  No big deal.

**Comment by moldover** [comment] 2019-07-06 20:02
closed via #336

**Closed by moldover** 2019-07-06 20:02 UTC
Labels: certification-deliverable, certification-deliverable-essential, needs-clarification, reviewed-by-chris, reviewed-by-george, reviewed-by-keith

**Comment by nealmcb** [comment] 2019-07-09 15:39
I don't see it noted previously, so I just wanted to also add some notes on the kind of **reproducability** that I think we're aiming for. It applies not just to testing and multiple runs of this software, and future versions of this software and of Java. Since this work is in support of the [VVSG: Voluntary Voting System Guidelines for Voting Equipment from the US Election Assistance Commission](https://www.eac.gov/voting-equipment/voluntary-voting-system-guidelines/), tallies of elections produced by this software should be reproducable via other applications that implement the VVSG standards for voting methods. I.e. jurisdictions around the world should be able to specify unambiguously in legislation their chosen parameters for ranked choice voting (IRV or STV), and any compatible piece of software should produce the same tally given a set of ballots and a specific random seed if necessary.
