### ISSUE TITLE
tabulation audit log files are ordered backward

### ISSUE THREAD

**Issue by tarheel** [BrightSpots/rcv#230] opened 2019-02-26 21:19 UTC
If I run a tabulation that generates audit logs in excess of the per-file limit of 50 MB, the logger numbers them in reverse of how they should be read. E.g. if there end up being 3 audit log files, the first one is _2, the second is _1, and the third is _0.

It would be more intuitive to order them the other way.

**Comment by moldover** [comment] 2019-02-28 03:34
Dupe of #125

**Closed by moldover** 2019-02-28 03:34 UTC
Labels: bug
