### ISSUE TITLE
handle Strict Open XML Spreadsheet files gracefully

### ISSUE THREAD

**Issue by tarheel** [BrightSpots/rcv#267] opened 2019-05-07 06:39 UTC
For some reason this format also uses the .xlsx extension. If you try to use one as a CVR, it'll trigger an exception in StreamingCVRReader.

`org.apache.poi.POIXMLException: Strict OOXML isn't currently supported, please see bug #57699`

**Comment by HEdingfield** [comment] 2019-05-07 15:53
@tarheel Would you mind posting an example CVR in that format here so we can repro easily?

**Comment by HEdingfield** [comment] 2019-05-07 16:20
[200Ballot6CandTestAlphaCand.zip](https://github.com/BrightSpots/rcv/files/3153598/200Ballot6CandTestAlphaCand.zip) should contain the files necessary to repro this (the config may need some modification first, e.g. with the file path).

**Comment by HEdingfield** [comment] 2019-05-07 16:23
George noted: the .xlsx file was originally provided as a .xlsd file and he just changed the extension.

**Comment by HEdingfield** [comment] 2019-05-08 18:20
PR #268 should fix somewhat-related issue #174, so this throws an error in the GUI now. Do we still want to keep this issue open so it throws a more friendly error than the one you enumerated in the first comment? Seems like it might be a bit overly-prescriptive to look for that specific exception and translate it into English, but up to you, @tarheel.

**Comment by moldover** [comment] 2019-05-09 16:18
We should always log the original exception (for debugging) but maybe it makes sense to also have a more generic message like "Failed to read CVR file for vendor ES&S.   This must be a valid .xlsx file" (something like that) which will nudge users in the right direction.

**Comment by tarheel** [comment] 2019-05-10 04:58
Yeah, now that we've identified this specific error case, it's worth the small effort to add logic to give the user clear guidance on how to fix it. I'll do this at some point.

**Comment by gngilbert** [comment] 2019-06-09 16:23
The reason I label this cert_del is that I think it is important for the certified version to provide, wherever possible, the kind of clear user guidance @tarheel mentioned.

**Comment by moldover** [comment] 2019-06-21 15:05
@tarheel I think it makes sense for me to do this along with #83 since it is pretty much one part of that task.  I'm going to assign to myself and am actually working on it now, so just let me know if you disagree.

**Comment by moldover** [comment] 2019-06-21 15:07
Actually, I'm just going to close this ticket as a dupe of #83 since it is already included in the description.

**Closed by moldover** 2019-06-21 15:07 UTC
Labels: bug, certification-deliverable, certification-deliverable-essential, reviewed-by-chris, reviewed-by-george, reviewed-by-keith
