### ISSUE TITLE
Possible issue with overvote label field? 

### ISSUE THREAD

**Issue by chughes297** [BrightSpots/rcv#740] opened 2023-07-17 17:31 UTC
On Windows 11 there may be a strange bug with overvote rule. I got this report from another RCVRC staffer running 1.4.0 on windows but haven't been able to recreate the issue on my macos machine. 

> I'm working on RCTab testing for ES&S, and I'm getting the following error messages:
> 
> 2023-07-11 17:07:12 MDT SEVERE: When overvoteLabel is supplied, overvoteRule must be either "Always skip to next rank" or "Exhaust immediately"!
> 2023-07-11 17:07:12 MDT SEVERE: overvoteDelimiter is required for an ES&S CVR source when overvoteRule is set to "Exhaust if multiple continuing".
> 2023-07-11 17:07:12 MDT SEVERE: Duplicate candidate names or aliases are not allowed:
> 2023-07-11 17:07:12 MDT SEVERE: Contest config validation failed! Please modify the contest config file and try again.
> 
> I've confirmed that a) the box for Overvote Label is empty, b) the box for overvoteDelimiter is correctly filled, and c) that there are no duplicate candidate names or aliases, but I still get these error messages. Any thoughts?

Here's the audit log and config file: 
https://drive.google.com/file/d/1r4Qe4HxXcBlusAxaRXFysrZnd2EG_RpM/view?usp=drive_link
https://drive.google.com/file/d/1yK6W5FCUzjPHf-zfz0SUkIo8weZr65Mv/view?usp=drive_link
CVR: [aliases_ess_xlsx_cvr.xlsx](https://github.com/BrightSpots/rcv/files/14386886/aliases_ess_xlsx_cvr.xlsx)

**Comment by yezr** [comment] 2024-02-22 16:58
> 2023-07-11 17:07:12 MDT SEVERE: Duplicate candidate names or aliases are not allowed:
looks like the #774 issue. 

The .config has `aliases_ess_xlsx_cvr.xlsx` configured as the CVR file. Do we have access to that file to perfectly recreate? 

I made a random .xlsx with the configured candidates and I wasn't able to recreate. Unless we can get the original CVR I think we might close this as cannot reproduce.

**Comment by yezr** [comment] 2024-02-23 15:30
Using the original config and CVR I can't repro anymore in 2.0 RC. Closing as can't repro.

**Closed** 2024-02-23 15:45 UTC
