### ISSUE TITLE
Envison the new UI!

### ISSUE THREAD

**Issue by CalebKleppner** [BrightSpots/rcv#87] opened 2018-07-25 22:38 UTC
I've uploaded a document that proposes a menu structure and tries to lay out many of the details.  Check it out and then let me know if you think we should change the approach or get started developing.

[Caleb UI Mockup 07.25.18.docx](https://github.com/BrightSpots/rcv/files/2229772/Caleb.UI.Mockup.07.25.18.docx)

**Comment by tarheel** [comment] 2018-07-29 03:41
Google Docs link to facilitate discussion: https://docs.google.com/document/d/1jQmhIoHNo0cNxD8h3xDHmiGyvxaUwbFi0Ieh3-W-2_U/

**Comment by HEdingfield** [comment] 2018-08-04 17:57
Closing because this is a duplicate of #45.

**Closed by HEdingfield** 2018-08-04 17:57 UTC
Labels: duplicate
