### ISSUE TITLE
Manually adding candidate names automatically adds a blank alias

### ISSUE THREAD

**Issue by chughes297** [BrightSpots/rcv#733] opened 2023-07-17 12:53 UTC
When manually adding candidates on the candidates tab, each candidate now automatically also gets a blank alias. This causes config validation to fail, which keeps tabulation from occurring. Here's links to a config file that generates this error and a .log of the error messages: 
[config file](https://drive.google.com/file/d/18ZrRsHavzbmu1-UANS9vGi0OZLS4kg25/view?usp=drive_link)
[.log file](https://drive.google.com/file/d/1U_icpTVmLOTCRgzwJ5-tqp9ojO3TMaOM/view?usp=drive_link)
[CVR](https://docs.google.com/spreadsheets/d/1fJ-NnirulztVoN6vAvX4ssI2muw09i6o/edit?usp=drive_link&ouid=116743718777594585909&rtpof=true&sd=true) - this is the same as the CVR in the test data

**Comment by joshadaniels** [comment] 2023-10-20 14:28
I have experienced this same problem. Also, I've had problems with auto-load candidates with ESS type CVR.

**Comment by tarheel** [comment] 2023-10-20 16:25
Or maybe @yezr can take a look first.

**Comment by yezr** [comment] 2023-10-20 21:09
I couldn't recreate by loading the config. I tried manually adding Candidates and it added them successfully with no aliases.

Chris can you add any more details on the way you used RCTab when this happened? What steps did you take? Does it happen every time?

**Comment by yezr** [comment] 2023-10-20 21:15
@joshadaniels I created #760 for ES&S candidate auto-loading separate from this issue.

**Comment by artoonie** [comment] 2024-01-16 22:24
@chughes297 I cannot access any of the three attached files, can you make them public?

My hunch is that this has to do with Windows line endings, maybe? Chris, were you using Windows?

**Comment by chughes297** [comment] 2024-01-17 13:20
ugh sorry, just made the links public. I was using macOS (happened on macOS 14), have not tested this on windows.

**Comment by artoonie** [comment] 2024-01-23 19:44
This was fixed in https://github.com/BrightSpots/rcv/issues/774 #775 

No wonder I couldn't reproduce :)

**Closed by artoonie** 2024-01-23 19:44 UTC
Labels: bug

**Comment by yezr** [comment] 2024-01-23 22:06
oops thats my bad on making a dupe. well, two issues closed for the price of one!
