### ISSUE TITLE
fix audit log path in output

### ISSUE THREAD

**Issue by tarheel** [BrightSpots/rcv#179] opened 2018-10-08 02:16 UTC
When tabulation completes, it says something like this:

2018-10-07 19:12:47 PDT INFO: Done logging tabulation to: /Users/leisenberg/code/rcv/test_output/multi_winner_2/2018-10-07_19-12-46_audit_%g.log

That %g is going to confuse people, and it doesn't seem necessary for a log file corresponding to a single tabulation (vs. the overall rcv.log file).

**Comment by moldover** [comment] 2018-10-26 15:14
dupe of https://github.com/BrightSpots/rcv/issues/158

**Closed by moldover** 2018-10-26 15:14 UTC
Labels: bug
